### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by stuta** [sacek/LPegLJ#12]
Hello. This is how I get memory leak. Normal lpeg does not leak memory.

```lua

local function find(str, pattern)
	if str == "" or not pattern or pattern == "" then
		return 0
	end
	if type(str) ~= "string" then
		loadRequire()
		util.printError(l("find value '%s' type is not a string", tostring(str)))
		-- str = tostring(str)
		return 0
	end
	local find
	if type(pattern) ~= "userdata" then
		find = P(pattern)
	else
		find = pattern
	end
	local notFind = (1 - find)
	local patt = notFind^0
	local pos = patt:match(str)
	if pos > #str then
		return 0
	end
	return pos
end


local printSkip = 1000
local pos,usedMem
for i = 1, math.huge do
	pos = find("asddfafadfadfa8d7fa0d9f8giås0df9gas+d0f9isdå+f0asd+f0asdf89uasidofaoisdf", "soi")
	if i == 1 or printSkip == 1 or i % printSkip == 1 then
		usedMem = util.round(collectgarbage("count"), 1)
		print("peg.find before collectgarbage: used memory: "..usedMem.." kb")
		collectgarbage()
		collectgarbage()
		collectgarbage()
		usedMem = util.round(collectgarbage("count"), 1)
		print("peg.find after collectgarbage: used memory: "..usedMem.." kb")
		print()
	end
end
```

**Comment by sacek** [comment]
Hello
I tested this example without memory leak (the average of used memory remained the same).
Test condition:
Ubuntu 16.04, LuaJIT 2.0.5 and LuaJIT 2.1.0-beta3.

**Comment by stuta** [comment]
I tested this with latest luajit, latest OSX, wine32 bit, wine64 bit and Ubuntu Mate, 100001 loops:

1. peg.find before collectgarbage: used memory: 455.2 kb
1. peg.find after collectgarbage: used memory: 433.8 kb
...
100001. peg.find before collectgarbage: used memory: 33277.1 kb
100001. peg.find after collectgarbage: used memory: 11019.4 k

**Comment by stuta** [comment]
The line leaking memory is local notFind = (1 - find). If I put  do return 0 end before it this does not leak memory. If I put  do return 0 end after it code leaks memory.

**Comment by stuta** [comment]
This is caused by something in my own require "start" code. When I test this outside my code then the memory leak does not happen.
