### ISSUE TITLE
LPegLJ vs LPeg performance

### ISSUE THREAD

**Issue by greatwolf** [sacek/LPegLJ#5]
Hi,

I just did some benchmark using the Language Benchmarks Game [**regex-dna script here**](http://benchmarksgame.alioth.debian.org/u32/program.php?test=regexdna&lang=lua&id=3).

Running the same script, using LPegLJ on LuaJIT-2.0.2, is about 5x slower than using the standard LPeg C implementation.
- LPegLJ:      ~105secs
- LPeg(-O2):  ~18.7secs
- LPeg(-O0):  ~36.0secs

It appears compiling LPeg even without optimizations still output performs LPegLJ by a large margin.

I wasn't expecting such a large performance difference. Any comments or suggestions on the matter?

**Comment by sacek** [comment]
I am working on version LPegLJ 0.12.3 now. I am trying generate optimalized source code for LuaJIT from LPeg patterns.  LPegLJ 0.12.3 (experimental version - not on github yet) on LuaJIT-2.x is 2.5x faster then LPeg C (-O2) implementation for Language Benchmarks Game regex-dna script.

**Comment by AdUki** [comment]
Great work! Looking forward to release version :) Will it improve also left recursion and memoization?

**Comment by sacek** [comment]
This experimental optimization not support left recursion and memoization yet.  There are "only" full compatibility with standard LPeg. Performance depends on type of patterns. On some patterns (finding, test alternatives) LPegLJ v 0.12.3 with experimental optimization is up to 10 times faster then standard LPeg, but on some complex grammars can be much slower. Also this experimental option not optimize work with captures yet.
